spring:
  application:
    name: example-app
  kafka:
    bootstrap-servers: localhost:9093,localhost:9094,localhost:9095
    producer:
      bootstrap-servers: "${spring.kafka.bootstrap-servers}"
      acks: all
      properties:
        enable.idempotence: true
        max.in.flight.requests.per.connection: 1
        transaction.timeout.ms: 5000
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: example-consumer-group-id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

example:
  inbound-topic-name: inbound.example.topic
  outbound-topic-name: outbound.example.topic
